services:
  postgres:
    image: postgres:13
    container_name: optisure_postgres
    environment:
      POSTGRES_USER: optisure
      POSTGRES_PASSWORD: password
      POSTGRES_DB: optisuredb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
